"""Base de dados inicial de comandos — Linux, Kubernetes e OpenStack.

Cada entrada: (comando, descrição, categoria, tags, exemplo).
Nos exemplos, os valores entre aspas ("...") são coisas que tens de
substituir pelos teus próprios valores (nomes, ficheiros, hosts, IPs) —
o resto é sintaxe fixa do comando.

`seed()` só insere se a base de dados estiver vazia, para nunca apagar
comandos que o utilizador já tenha adicionado ou editado.
"""

import db

LINUX = [
    ("ls -la", "Lista ficheiros e pastas com detalhes, incluindo ocultos",
     "listar ficheiros diretoria pasta ver", "ls -la /var/log"),
    ("cd", "Muda de diretoria de trabalho",
     "navegar diretoria pasta mudar", "cd /etc/nginx"),
    ("pwd", "Mostra o caminho completo da diretoria atual",
     "onde estou caminho atual localizacao", ""),
    ("cp -r", "Copia ficheiros ou pastas, recursivamente",
     "copiar duplicar", 'cp -r "/origem" "/destino"'),
    ("mv", "Move ou renomeia ficheiros e pastas",
     "mover renomear", 'mv "ficheiro.txt" "/nova/pasta/"'),
    ("rm -rf", "Remove ficheiros ou pastas recursivamente e sem confirmação — usar com cuidado",
     "apagar eliminar remover", 'rm -rf "/tmp/teste"'),
    ("mkdir -p", "Cria uma diretoria, incluindo diretorias pai em falta",
     "criar pasta diretoria", 'mkdir -p "/var/app/logs"'),
    ("find", "Procura ficheiros por nome, tipo, tamanho ou data",
     "procurar localizar ficheiro pesquisar", 'find / -name "*.log" -mtime -1'),
    ("grep -r", "Procura um padrão de texto dentro de ficheiros, recursivamente",
     "procurar texto pesquisar padrao logs", 'grep -r "error" /var/log'),
    ("chmod", "Altera as permissões de leitura/escrita/execução de um ficheiro",
     "permissoes acesso executar", 'chmod 755 "script.sh"'),
    ("chown", "Altera o dono e/ou grupo de um ficheiro",
     "dono proprietario grupo permissoes", 'chown "user:group" "ficheiro"'),
    ("ps aux", "Lista todos os processos em execução no sistema",
     "processos listar pid", ""),
    ("top", "Monitoriza processos e uso de CPU/memória em tempo real",
     "monitorizar desempenho recursos processos", ""),
    ("htop", "Versão interativa e mais legível do top",
     "monitorizar desempenho recursos processos", ""),
    ("kill -9", "Termina um processo à força, pelo PID",
     "matar terminar processo forcar", 'kill -9 "1234"'),
    ("systemctl status", "Mostra o estado atual de um serviço systemd",
     "servico estado diagnosticar", 'systemctl status "nginx"'),
    ("systemctl restart", "Reinicia um serviço systemd",
     "servico reiniciar", 'systemctl restart "nginx"'),
    ("systemctl enable", "Ativa o arranque automático de um serviço no boot",
     "servico arranque automatico boot", 'systemctl enable "nginx"'),
    ("journalctl -u", "Mostra os logs de um serviço systemd específico",
     "logs registo servico diagnosticar", 'journalctl -u "nginx" -f'),
    ("ip addr", "Mostra os endereços IP configurados nas interfaces de rede",
     "rede ip interface", ""),
    ("ss -tulnp", "Lista as portas/sockets de rede em escuta",
     "rede portas escuta diagnosticar", 'ss -tulnp | grep "443"'),
    ("curl -I", "Faz um pedido HTTP e mostra só os cabeçalhos da resposta",
     "rede http teste pedido", 'curl -I "https://exemplo.com"'),
    ("ping", "Testa a conectividade de rede a um host",
     "rede testar conectividade diagnosticar", 'ping -c 4 "8.8.8.8"'),
    ("dig", "Resolve nomes DNS e mostra detalhes da resposta",
     "dns resolver nome rede", 'dig "exemplo.com"'),
    ("ssh", "Liga-se a outra máquina através de SSH",
     "ligar remoto shell terminal", 'ssh "utilizador@host"'),
    ("scp", "Copia ficheiros entre máquinas através de SSH",
     "copiar remoto rede ficheiro", 'scp "ficheiro.txt" "utilizador@host:/destino/"'),
    ("rsync -avz", "Sincroniza ficheiros/pastas, localmente ou entre máquinas",
     "sincronizar copiar backup", 'rsync -avz "/origem/" "utilizador@host:/destino/"'),
    ("df -h", "Mostra o espaço em disco usado e livre, em formato legível",
     "disco espaco armazenamento", ""),
    ("du -sh", "Mostra o tamanho total de uma pasta",
     "disco tamanho pasta espaco", "du -sh /var/log"),
    ("tar -czvf", "Cria um arquivo comprimido (.tar.gz)",
     "comprimir arquivar backup", 'tar -czvf "backup.tar.gz" "/pasta"'),
    ("tar -xzvf", "Extrai um arquivo comprimido (.tar.gz)",
     "descomprimir extrair", 'tar -xzvf "backup.tar.gz"'),
    ("tail -f", "Mostra as últimas linhas de um ficheiro e continua a segui-lo em tempo real",
     "logs seguir ficheiro monitorizar", "tail -f /var/log/syslog"),
    ("less", "Vê o conteúdo de um ficheiro página a página",
     "ver ficheiro conteudo ler", "less /var/log/syslog"),
    ("free -h", "Mostra a memória RAM usada e livre",
     "memoria ram recursos", ""),
    ("uptime", "Mostra há quanto tempo o sistema está ligado e a carga média",
     "tempo atividade carga sistema", ""),
    ("crontab -e", "Edita as tarefas agendadas do utilizador atual",
     "agendar tarefa cron periodico", ""),
    ("sudo -l", "Lista os comandos que o utilizador pode correr com sudo",
     "permissoes sudo administrador", ""),
    ("apt update && apt install", "Atualiza a lista de pacotes disponíveis e instala um pacote",
     "instalar pacote debian ubuntu software", 'apt update && apt install "nginx"'),
    ("lsblk", "Lista os discos e partições do sistema",
     "disco particao dispositivo armazenamento", ""),
    ("mount", "Monta um sistema de ficheiros num ponto de montagem",
     "montar disco particao", 'mount "/dev/sdb1" "/mnt/dados"'),
]

KUBERNETES = [
    ("kubectl get pods", "Lista os pods do namespace atual",
     "listar pods estado", 'kubectl get pods -n "default"'),
    ("kubectl get pods -A", "Lista os pods de todos os namespaces",
     "listar pods todos namespaces", ""),
    ("kubectl get nodes", "Lista os nós (máquinas) do cluster",
     "listar nos cluster maquinas", ""),
    ("kubectl describe pod", "Mostra detalhes completos e eventos recentes de um pod",
     "detalhes eventos diagnosticar debug", 'kubectl describe pod "meu-pod"'),
    ("kubectl logs", "Mostra os logs de um pod/contentor",
     "logs registo diagnosticar", 'kubectl logs "meu-pod" -f'),
    ("kubectl logs --previous", "Mostra os logs da instância anterior de um contentor, útil depois de um crash",
     "logs crash anterior diagnosticar", 'kubectl logs "meu-pod" --previous'),
    ("kubectl exec -it", "Abre um shell interativo dentro de um pod",
     "entrar shell terminal aceder", 'kubectl exec -it "meu-pod" -- /bin/bash'),
    ("kubectl apply -f", "Aplica um manifesto YAML, criando ou atualizando os recursos nele descritos",
     "aplicar criar atualizar manifesto yaml", 'kubectl apply -f "deployment.yaml"'),
    ("kubectl delete", "Apaga um recurso do cluster",
     "apagar eliminar remover", 'kubectl delete pod "meu-pod"'),
    ("kubectl create", "Cria um recurso diretamente, sem ficheiro YAML",
     "criar recurso", 'kubectl create namespace "teste"'),
    ("kubectl edit", "Abre um recurso existente no editor para o alterar em tempo real",
     "editar alterar recurso", 'kubectl edit deployment "meu-app"'),
    ("kubectl get svc", "Lista os serviços (Service) do namespace",
     "listar servicos rede", ""),
    ("kubectl get deployments", "Lista os deployments do namespace",
     "listar deployments", ""),
    ("kubectl get namespaces", "Lista todos os namespaces do cluster",
     "listar namespaces", ""),
    ("kubectl get events --sort-by=.lastTimestamp", "Lista os eventos recentes do cluster, ordenados por hora",
     "eventos diagnosticar cluster historico", ""),
    ("kubectl scale", "Ajusta o número de réplicas de um deployment",
     "escalar replicas aumentar diminuir", 'kubectl scale deployment "meu-app" --replicas=3'),
    ("kubectl rollout status", "Mostra o progresso de um rollout em curso",
     "rollout deploy progresso estado", 'kubectl rollout status "deployment/meu-app"'),
    ("kubectl rollout undo", "Reverte um deployment para a revisão anterior",
     "reverter rollback desfazer", 'kubectl rollout undo "deployment/meu-app"'),
    ("kubectl rollout restart", "Reinicia todos os pods de um deployment, um a um",
     "reiniciar deployment", 'kubectl rollout restart "deployment/meu-app"'),
    ("kubectl port-forward", "Encaminha uma porta local para um pod, para aceder localmente",
     "porta encaminhar aceder tunel", 'kubectl port-forward "pod/meu-pod" 8080:80'),
    ("kubectl top pods", "Mostra o uso de CPU/memória de cada pod",
     "recursos cpu memoria monitorizar", ""),
    ("kubectl top nodes", "Mostra o uso de CPU/memória de cada nó",
     "recursos cpu memoria monitorizar no", ""),
    ("kubectl config get-contexts", "Lista os contextos (clusters/utilizadores) configurados localmente",
     "contexto cluster configuracao listar", ""),
    ("kubectl config use-context", "Muda para outro contexto (cluster)",
     "mudar contexto cluster trocar", 'kubectl config use-context "producao"'),
    ("kubectl cp", "Copia ficheiros entre a máquina local e um pod",
     "copiar ficheiro pod", 'kubectl cp "ficheiro.txt" "meu-pod:/tmp/"'),
    ("kubectl label", "Adiciona ou altera labels (etiquetas) de um recurso",
     "label etiqueta metadata", 'kubectl label pod "meu-pod" ambiente="producao"'),
    ("kubectl annotate", "Adiciona ou altera anotações de um recurso",
     "anotacao metadata", 'kubectl annotate pod "meu-pod" descricao="pod de teste"'),
    ("kubectl cordon", "Marca um nó como não-agendável, para não receber novos pods",
     "no manutencao bloquear agendamento", 'kubectl cordon "meu-no"'),
    ("kubectl drain", "Esvazia um nó, movendo os pods para outros nós, antes de manutenção",
     "no manutencao esvaziar", 'kubectl drain "meu-no" --ignore-daemonsets'),
    ("kubectl uncordon", "Volta a permitir que um nó receba novos pods",
     "no manutencao desbloquear", 'kubectl uncordon "meu-no"'),
    ("kubectl explain", "Mostra a documentação de um recurso ou campo de um manifesto",
     "documentacao ajuda campo yaml", "kubectl explain pod.spec.containers"),
    ("kubectl get all", "Lista os recursos mais comuns (pods, services, deployments) de um namespace",
     "listar tudo namespace resumo", ""),
    ("helm install", "Instala um chart Helm no cluster",
     "helm instalar pacote chart", 'helm install "minha-app" "./chart"'),
    ("helm upgrade", "Atualiza uma instalação Helm existente",
     "helm atualizar chart", 'helm upgrade "minha-app" "./chart"'),
    ("helm list", "Lista as instalações (releases) Helm ativas",
     "helm listar releases", ""),
    ("helm uninstall", "Remove uma instalação Helm",
     "helm remover desinstalar", 'helm uninstall "minha-app"'),
]

OPENSTACK = [
    ("openstack server list", "Lista as instâncias (VMs) do projeto atual",
     "listar vm instancia servidor", ""),
    ("openstack server show", "Mostra detalhes completos de uma instância",
     "detalhes vm instancia", 'openstack server show "meu-servidor"'),
    ("openstack server create", "Cria uma nova instância",
     "criar vm instancia",
     'openstack server create --image "ubuntu" --flavor "m1.small" --network "priv" "meu-servidor"'),
    ("openstack server delete", "Apaga uma instância",
     "apagar vm eliminar instancia", 'openstack server delete "meu-servidor"'),
    ("openstack server reboot", "Reinicia uma instância",
     "reiniciar vm instancia", 'openstack server reboot "meu-servidor"'),
    ("openstack server stop", "Para uma instância (desliga)",
     "parar desligar vm instancia", 'openstack server stop "meu-servidor"'),
    ("openstack server start", "Arranca uma instância parada",
     "arrancar ligar vm instancia", 'openstack server start "meu-servidor"'),
    ("openstack network list", "Lista as redes do projeto",
     "listar rede", ""),
    ("openstack network create", "Cria uma rede",
     "criar rede", 'openstack network create "minha-rede"'),
    ("openstack subnet create", "Cria uma sub-rede dentro de uma rede",
     "criar subrede rede",
     'openstack subnet create --network "minha-rede" --subnet-range "10.0.0.0/24" "minha-subrede"'),
    ("openstack router create", "Cria um router",
     "criar router", 'openstack router create "meu-router"'),
    ("openstack router set --external-gateway", "Liga um router a uma rede externa (dá-lhe saída para a internet)",
     "router gateway externo internet", 'openstack router set --external-gateway "ext-net" "meu-router"'),
    ("openstack floating ip create", "Cria um IP flutuante (público)",
     "criar ip flutuante publico", 'openstack floating ip create "ext-net"'),
    ("openstack floating ip list", "Lista os IPs flutuantes do projeto",
     "listar ip flutuante publico", ""),
    ("openstack server add floating ip", "Associa um IP flutuante a uma instância",
     "associar ip publico vm instancia", 'openstack server add floating ip "meu-servidor" "203.0.113.10"'),
    ("openstack volume list", "Lista os volumes (discos) do projeto",
     "listar volume disco", ""),
    ("openstack volume create", "Cria um volume (disco)",
     "criar volume disco", 'openstack volume create --size 10 "meu-volume"'),
    ("openstack server add volume", "Associa um volume a uma instância",
     "associar volume disco vm instancia", 'openstack server add volume "meu-servidor" "meu-volume"'),
    ("openstack image list", "Lista as imagens disponíveis para criar instâncias",
     "listar imagem", ""),
    ("openstack image create", "Regista uma nova imagem",
     "criar imagem registar", 'openstack image create --file "ubuntu.qcow2" --disk-format qcow2 "minha-imagem"'),
    ("openstack flavor list", "Lista os \"flavors\" (tamanhos de VM: CPU/RAM/disco) disponíveis",
     "listar flavor tamanho vm", ""),
    ("openstack security group create", "Cria um grupo de segurança (firewall)",
     "criar firewall seguranca grupo", 'openstack security group create "meu-grupo"'),
    ("openstack security group rule create", "Adiciona uma regra a um grupo de segurança",
     "regra firewall porta permitir",
     'openstack security group rule create --proto tcp --dst-port 22 "meu-grupo"'),
    ("openstack project list", "Lista os projetos (tenants)",
     "listar projeto tenant", ""),
    ("openstack project create", "Cria um novo projeto",
     "criar projeto tenant", 'openstack project create "meu-projeto"'),
    ("openstack user list", "Lista os utilizadores",
     "listar utilizador", ""),
    ("openstack keypair create", "Cria um par de chaves SSH e regista a chave pública",
     "criar chave ssh par", 'openstack keypair create "minha-chave" > "minha-chave.pem"'),
    ("openstack stack list", "Lista as stacks Heat (recursos criados por orquestração)",
     "listar stack heat orquestracao", ""),
    ("openstack token issue", "Emite um token de autenticação para usar noutras chamadas",
     "autenticacao token emitir", ""),
    ("source openrc.sh", "Carrega as credenciais e variáveis de ambiente necessárias para usar o CLI OpenStack",
     "credenciais autenticar ambiente variaveis", ""),
]


def seed():
    """Insere a base inicial de comandos, só se a base de dados ainda
    estiver vazia — nunca apaga nem duplica o que o utilizador já tenha."""
    if db.count_commands() > 0:
        return 0

    inserted = 0
    for entries, category in ((LINUX, "Linux"), (KUBERNETES, "Kubernetes"), (OPENSTACK, "OpenStack")):
        for command, description, tags, example in entries:
            db.add_command(command, description, category, tags, example)
            inserted += 1
    return inserted
